import Head from "next/head";
import { Inter } from "@next/font/google";
import MyTasks from "../Components/Header/MyTasks";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const app = initFirebase();
  return (
    <>
      <Head>
        <title>Add Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container pt-20">
        <MyTasks />
        <MyTasks />
        <MyTasks />
        <MyTasks />
      </div>
    </>
  );
}
